upstream isa_backend {
    server api-replica-1:8080;
    server api-replica-2:8080;
}

server {
    listen 80;

    location / {
        proxy_pass http://isa_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}