global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'isa-application'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-replica-1:8080', 'api-replica-2:8080']